### ISSUE TITLE
Support condensed for loops

### ISSUE THREAD

**Issue by haampie** [GunnarFarneback/Multibreak.jl#1]
The package does not work with

```julia
using Multibreak

@multibreak for i = 1:100, j = 1:100
  if (5i + 7j) % 11 == 1
    break; continue
  end
end
```

errors with 
```ERROR: multibreak: not enough nested loops for requested multiple break/continue```

**Comment by GunnarFarneback** [comment]
Well, it is only one loop. A single `break` ends it all and it would be surprising if `break; continue` did less. See also the [documentation](https://github.com/GunnarFarneback/Multibreak.jl/blob/46e410820d994033c8ad52c533200db4bcccd90f/test/tutorial.jl#L259-L302).

**Comment by haampie** [comment]
Right, you could argue that wrapping this kind of loop in `@multibreak` would give you finer control than what julia itself currently does

**Comment by GunnarFarneback** [comment]
It could but I would find it rather confusing.
